#JVM for Kafka and Craft
jvm_package: openjdk-11-jdk


#kafka user
kafka_user: kafka


# install kafka home folder
kafka_folder: /opt/kafka


# Kafka JVM
kafka_heap_opts: -Xmx256M -Xms128M
kafka_jmx_opts: -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.net.preferIPv4Stack=true -Dcom.sun.management.jmxremote.port=9990
kafka_gc_log_opts: 
kafka_opts:


# Kafka additional config
kafka_additional_config: {}
#  message.max.bytes: 1000

kafka_topics: []
# - name: topic1
# - name: topic2
#   replication_factor: 3
#   partitions: 10

# Socket Server Settings
kafka_num_network_threads: 3
kafka_num_io_threads: 8
kafka_socket_send_buffer_bytes: 102400
kafka_socket_recieve_buffer_bytes: 102400
kafka_socket_request_max_bytes: 104857600
kafka_inter_broker_listener_name: PLAINTEXT
kafka__listeners: []
#  - PLAINTEXT://:9092
#  - CONTROLLER://:9093

## Log retention policy
kafka_log_retention_hours: 24
kafka_log_retention_bytes: 0 # when set to zero this setting is ignored
kafka_log_retention_check_interval_ms: 300000
kafka_log_segment_bytes: 1073741824

## Log basics
kafka_num_partitions: 1
kafka_log_dirs: 
  - /opt/kafka/logs

## Server basics
kafka_node_roles:
  - broker
  - controller

## Internal topic settings
kafka_offsets_topic_replication_factor: 1
kafka_transaction_state_log_replication_factor: 1
kafka_transaction_state_log_min_isr: 1
