version: '3.1'
services:
  db:
    image: mariadb
    container_name: mydb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD : ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
